name: Continuous Integration
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup PatchVer
      uses: diamonddrakeventures/setup-patchver@e953dc23d1e17147b4f6a289d53d6e5e50385ae2
      with:
        patchver-version: 0.1.0
    - name: Run PatchVer
      run: patchver patched-mods
    - name: Upload patched mods
      uses: actions/upload-artifact@v4
      with:
        name: patched-mods
        path: patched-mods
