name: Continuous Integration
on:
  push:
    paths:
      - ".github/workflows/ci.yaml"
      - "config.json"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup PatchVer
      uses: diamonddrakeventures/setup-patchver@v0.1
      with:
        patchver-version: 0.1.0
    - name: Run PatchVer
      run: patchver patched-mods
    - name: Upload patched mods
      uses: actions/upload-artifact@v4
      with:
        name: patched-mods
        path: patched-mods
    - uses: s3-actions/s3cmd@v1.5.0
      with:
        provider: ${{ vars.S3_PROVIDER }}
        region: ${{ vars.S3_REGION }}
        access_key: ${{ secrets.S3_ACCESS_KEY }}
        secret_key: ${{ secrets.S3_SECRET_KEY }}
    - name: Upload mods to S3
      env:
        OUTPUT: ${{ vars.S3_BUCKET }}/
      run: s3cmd put --acl-public patched-mods/* "$OUTPUT"
